services:
  ckn-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ckn-daemon
    ports:
      - "8080:8080"
    privileged: true
    pid: host
    environment:
      - POWER_CSV=/logs/power.csv
      - RESULTS_CSV=/logs/mobilenet_v3_small.csv
      - TRAPS_POWER_BACKEND=tegrastats
      - TZ=America/New_York
      - CKN_KAFKA_BROKER=149.165.170.250:9092
    volumes:
      - .:/logs
      - ./uploads:/app/uploads
      - /run/jtop.sock:/run/jtop.sock
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "python3 /app/power_logger.py & python3 /app/server.py"